apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend-farm
 labels:
   app: backend-farm
spec:
 replicas: 1
 selector:
   matchLabels:
     app: backend-farm
 template:
   metadata:
     labels:
       app: backend-farm
   spec:
     containers:
     - name: farm-fastapi
       image: apurvbidkar/microservice:farm_fastapi
       imagePullPolicy: IfNotPresent
       ports:
       - containerPort: 8000
